// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Votes     int    `json:"votes"`
	URL       string `json:"url"`
	CreatedAt string `json:"createdAt"`
}

type PostsMeta struct {
	Count int `json:"count"`
}

type OrderBy string

const (
	OrderByCreatedAtAsc  OrderBy = "createdAt_ASC"
	OrderByCreatedAtDesc OrderBy = "createdAt_DESC"
)

var AllOrderBy = []OrderBy{
	OrderByCreatedAtAsc,
	OrderByCreatedAtDesc,
}

func (e OrderBy) IsValid() bool {
	switch e {
	case OrderByCreatedAtAsc, OrderByCreatedAtDesc:
		return true
	}
	return false
}

func (e OrderBy) String() string {
	return string(e)
}

func (e *OrderBy) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderBy", str)
	}
	return nil
}

func (e OrderBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
